---
title: "Test Full Model"
author: "Alex Cope"
date: '2023-07-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PCMBase,lib.loc = "~/R_dev")
library(PCMBaseCpp)
library(LaplacesDemon,lib.loc = "~/R_dev/")
require(coda)
library(tidyverse)
library(cowplot)
library(ggpubr)
library(phytools)
library(extraDistr)
source("/data2/cope/rna-protein-coevolution/R_notebooks/local_functions.R")


```
# Test full model 

```{r}
ModelOUOU_full_model <- function(parm, Data)
{
  
  ### Parameters
  ## Means are for a lognormal distribution, represent mean on the log-scale. Can be negative.
  hy.mean.prior <- parm[Data[["pos.hy.mean"]]]
  hy.std.prior <- exp(parm[Data[["pos.hy.std"]]])
  
  hx.mean.prior <- parm[Data[["pos.hx.mean"]]]
  hx.std.prior <- exp(parm[Data[["pos.hx.std"]]])
  
  b.mean.prior <- parm[Data[["pos.b.mean"]]]
  b.std.prior <- exp(parm[Data[["pos.b.std"]]])
  
  sigmay.mean.prior <- parm[Data[["pos.sigmay.mean"]]]
  sigmay.std.prior <- exp(parm[Data[["pos.sigmay.std"]]])
  
  sigmax.mean.prior <- parm[Data[["pos.sigmax.mean"]]]
  sigmax.std.prior <- exp(parm[Data[["pos.sigmax.std"]]])
  
  hy <- exp(parm[Data[["pos.hy"]]])
  hx <- exp(parm[Data[["pos.hx"]]])
  b <- parm[Data[["pos.b"]]]
  sigmay <- exp(parm[Data[["pos.sigmay"]]])
  sigmax <- exp(parm[Data[["pos.sigmax"]]])
  pos.psi <- Data[["pos.psi"]]
  
  ll_fun <- Data[["ll_fun"]]
  prop <- Data[["prop"]]
  gene.ll <- Data[["Gene.LL"]]
  offset <- 10
  ## Can use pos.psi[1] as check because parm should first have hyperparameters and then gene-specific parameters
  if (prop[1] >= pos.psi[1] && !is.null(gene.ll))
  {
    gene.index <- floor((prop[1] - offset - 1)/7) + 1
    other.ll <- sum(gene.ll[-gene.index])
    current.ll <- ll_fun[[gene.index]](c(parm[prop[1]] + parm[prop[5]]*parm[prop[2]],
                                         parm[prop[2]],
                                         exp(parm[prop[3]]),
                                         0,
                                         -exp(parm[prop[3]]) * parm[prop[5]],
                                         exp(parm[prop[4]]),
                                         parm[prop[1]] + parm[prop[5]]*parm[prop[2]],
                                         parm[prop[2]],
                                         exp(parm[prop[6]]),
                                         exp(parm[prop[7]])))
  
    LL <- current.ll + other.ll
    gene.ll[gene.index] <- current.ll
  } else {
    num.genes <- (length(parm)-offset)/7
    gene.ll <- unlist(lapply(1:num.genes, function(current.loci)
    {
      par.index <- offset + 7*(current.loci-1) + 1
      ll <- ll_fun[[current.loci]](c(parm[par.index] + parm[par.index+4]*parm[par.index+1],
                                     parm[par.index+1],
                                     exp(parm[par.index+2]),
                                     0,
                                     -exp(parm[par.index+2]) * parm[par.index+4],
                                     exp(parm[par.index+3]),
                                     parm[par.index] + parm[par.index+4]*parm[par.index+1],
                                     parm[par.index+1],
                                     exp(parm[par.index+5]),
                                     exp(parm[par.index+6])))
      
      ll
    })
    )
    LL <- sum(gene.ll)
  }
  
  PR <- sum(dlnorm(hy,hy.mean.prior,hy.std.prior,log=T)) +
    sum(dlnorm(hx,hx.mean.prior,hx.std.prior,log=T)) +
    sum(dlnorm(sigmay,sigmay.mean.prior,sigmay.std.prior,log=T)) +
    sum(dlnorm(sigmax,sigmax.mean.prior,sigmax.std.prior,log=T)) +
    sum(dnorm(b,mean = b.mean.prior,sd = b.std.prior,log=T)) +
    sum(dnorm(parm[pos.psi],mean = 0,sd = 1,log=T))
  
  HYP <- sum(dhcauchy(c(sigmay.std.prior,
                     sigmax.std.prior,
                     b.std.prior,
                     hx.std.prior,
                     hy.std.prior),
                     sigma=1,log=T)) +
         sum(dunif(c(hy.mean.prior,
               hx.mean.prior,
               sigmay.mean.prior,
               sigmax.mean.prior),min=log(0.008),max=0,log=T)) +
         dnorm(b.mean.prior,mean=0,sd=1,log=T)
  LP.unc <- LL + PR + HYP
  ## Apply correction for log-transformation of hyperparameters. Using lognormal for other parameters already corrects for this, but currently using uniform for hyperparameters
  LP <- LP.unc + sum(log(c(hy.std.prior,
                       hx.std.prior,
                       b.std.prior,
                       sigmay.std.prior,
                       sigmax.std.prior)))# + sum(c(hy,hx,sigmay,sigmax))
  
  ## Parameter.LL is a bit of misnomer, is actually log posterior for each gene (no hyperpriors)
  Modelout <- list(LP=LP,Dev=-2*LL, Monitor=c(LP,LP.unc,LL,PR,HYP), yhat=1, parm=parm,Parameter.LL=gene.ll)
  return(Modelout)
}




```



## Test full model on data simulated under simple model

```{r}
options(PCMBase.Threshold.EV = 1e-07)
options(PCMBase.Threshold.SV = 1e-08)
num.loci <- 50 # number of loci
model.type <- "OU__Global_X0__Global_H__Theta__Diagonal_WithNonNegativeDiagonal_Sigma_x__Omitted_Sigmae_x"
ba.tree <- ape::read.nexus("../Data/tree_11sp_noGpig.nex")
ba.tree <- phytools::force.ultrametric(ba.tree,method = "extend") # tree is not ultrametric due to apparent rounding error
min.edge <- min(ba.tree$edge.length)
ba.tree <- pbtree(n = 50,scale = unname(tip.heights[1]))
ba.tree <- paleotree::minBranchLength(ba.tree,min.edge,modifyRootAge = F)

num.species <- length(ba.tree$tip.label)
# Simulate the optima of the 2 traits across loci
psi.x <- rnorm(n=num.loci,mean=0,sd=1)
psi.y <- rnorm(n=num.loci,mean=0,sd=1)

sigma.x.mean <- -2.8
sigma.y.mean <- -2.1
alpha.x.mean <- -3.8
alpha.y.mean <- -3.2
b.mean <- 0.65

data.pcm <- vector(mode="list",length=num.loci)
likFun.list <- vector(mode="list",length=num.loci)
true.param <- c(alpha.y.mean,log(1.5),alpha.x.mean,log(1.5),b.mean,log(0.25),sigma.y.mean,log(1.5),sigma.x.mean,log(1.5))
names(true.param) <- c("H_Y_Mean","H_Y_Std","H_X_Mean","H_X_Std","Q_Mean","Q_Std","Sigma_Y_Mean","Sigma_Y_Std","Sigma_X_Mean","Sigma_X_Std")
for(j in 1:num.loci)
{
  ## Get root state
  x0 <- psi.x[j]
  y0 <- psi.y[j] + b.mean*x0
  true.model <- PCM(model=model.type,k=2)
  param <- c(y0,
             x0,
             exp(alpha.y.mean),
             0,
            -b.mean*exp(alpha.y.mean),
             exp(alpha.x.mean),
             y0,
             x0,
             exp(sigma.y.mean),
             exp(sigma.x.mean))
  PCMParamLoadOrStore(true.model, param, offset=0, load=T)
  
  gene.param <- c(psi.y[j],psi.x[j],alpha.y.mean,alpha.x.mean,b.mean,sigma.y.mean,sigma.x.mean)
  names(gene.param) <- paste0(c("Psi_Y_","Psi_X_","H_Y_","H_X_","Q_","Sigma_Y_","Sigma_X_"),j)
  true.param <- c(true.param,gene.param)
  modelOU <- PCM(model= model.type,k=2)
  data.pcm[[j]] <- PCMSim(tree = ba.tree,model = true.model,X0 = true.model$X0)
  data.pcm[[j]] <- data.pcm[[j]][,1:num.species]
  likFun.list[[j]] <- PCMCreateLikelihood(data.pcm[[j]], ba.tree,modelOU,metaI = PCMInfoCpp)
} 

```


```{r}

start.values <- true.param

pos.hy.mean <- grep("H_Y_Mean",names(start.values)) 
pos.hy.std <- grep("H_Y_Std",names(start.values)) 
pos.hx.mean <- grep("H_X_Mean",names(start.values)) 
pos.hx.std <- grep("H_X_Std",names(start.values)) 

pos.sigmay.mean <- grep("Sigma_Y_Mean",names(start.values)) 
pos.sigmay.std <- grep("Sigma_Y_Std",names(start.values)) 
pos.sigmax.mean <- grep("Sigma_X_Mean",names(start.values)) 
pos.sigmax.std <- grep("Sigma_X_Std",names(start.values)) 

pos.b.std <- grep("Q_Std",names(true.param))
pos.b <- grep("Q_[0-9]+",names(true.param))

pos.hx <- grep("H_X_[0-9]+",names(start.values)) 
pos.hy <- grep("H_Y_[0-9]+",names(start.values)) 
pos.b <- grep("Q_Mean",names(start.values))
pos.sigmax <- grep("Sigma_X_[0-9]+",names(start.values))
pos.sigmay <- grep("Sigma_Y_[0-9]+",names(start.values))

pos.psi <- grep("Psi",names(start.values))

MyData_OUOU <- list(ll_fun = likFun.list,
                    mon.names = c("LP","LP.unc","LL","PR","HYP"),
                    parm.names=names(start.values), 
                    pos.hy.mean = pos.hy.mean,
                    pos.hy.std = pos.hy.std,
                    pos.hx.mean = pos.hx.mean,
                    pos.hx.std = pos.hx.std,
                    pos.b.mean = pos.b.mean,
                    pos.b.std = pos.b.std,
                    pos.sigmay.mean = pos.sigmay.mean,
                    pos.sigmay.std = pos.sigmay.std, 
                    pos.sigmax.mean = pos.sigmax.mean,
                    pos.sigmax.std = pos.sigmax.std,
                    pos.hy = pos.hy, 
                    pos.hx = pos.hx, 
                    pos.b = pos.b,
                    pos.sigmax=pos.sigmax,
                    pos.sigmay=pos.sigmay,
                    pos.psi=pos.psi,
                    prop = 1:length(start.values),
                    N=length(ba.tree$tip.label)*num.loci*2)



blockwise.sample.list <- list()
blockwise.sample.list[[1]] <- c(3,4,9,10)
blockwise.sample.list[[2]] <- c(5,6)
blockwise.sample.list[[3]] <- c(1,2,7,8)
num.block <- length(blockwise.sample.list)
for (i in 1:num.loci)
{
  pos.psi.i <- grep(paste0("Psi_[YX]_",i,"$"),names(start.values))
  pos.h.i <- grep(paste0("H_[YX]_",i,"$"),names(start.values))
  pos.q.i <- grep(paste0("Q_",i,"$"),names(start.values))
  pos.sigma.i <- grep(paste0("Sigma_[YX]_",i,"$"),names(start.values))
  blockwise.sample.list[[i+num.block]] <- c(pos.psi.i,pos.h.i,pos.q.i,pos.sigma.i)
}

adapt.fit.full.sim.simple <- LaplacesDemon_local(ModelOUOU_full_model,
                                   MyData_OUOU,
                                   Initial.Values = start.values,
                                   Iterations = 10000,
                                   Algorithm = "RAM",
                                   Thinning = 1,
                                   Debug = list(DB.Model = F,
                                                DB.chol = T),
                                   Specs = list(alpha.star = 0.35,
                                                B = blockwise.sample.list,
                                                Dist="t",
                                                gamma = 2/3,
                                                n=0
                                   ))





```

```{r}
plot(adapt.fit.full.sim.simple$Monitor[,"LP"],type="l",main="Log(Posterior)")
plot(adapt.fit.full.sim.simple$Monitor[,"LL"],type="l",main="Log(Likelihood)")
plot(adapt.fit.full.sim.simple$Monitor[,"PR"],type="l",main="Log(Prior)")
plot(adapt.fit.full.sim.simple$Posterior1[,"H_Y_Mean"],type="l",main="H_Y_Mean")
abline(h=alpha.y.mean)
plot(adapt.fit.full.sim.simple$Posterior1[,"H_Y_Std"],type="l",main="H_Y_Std")
plot(adapt.fit.full.sim.simple$Posterior1[,"H_X_Mean"],type="l",main="H_X_Mean")
abline(h=alpha.x.mean)
plot(adapt.fit.full.sim.simple$Posterior1[,"H_X_Std"],type="l",main="H_X_Std")
plot(adapt.fit.full.sim.simple$Posterior1[,"Q_Mean"],type="l",main="Q_Mean")
abline(h=0.65)
plot(adapt.fit.full.sim.simple$Posterior1[,"Q_Std"],type="l",main="Q_Std")
plot(adapt.fit.full.sim.simple$Posterior1[,"Sigma_Y_Mean"],type="l",main="Sigma_Y_Mean")
abline(h=sigma.y.mean)
plot(adapt.fit.full.sim.simple$Posterior1[,"Sigma_Y_Std"],type="l",main="Sigma_Y_Std")
plot(adapt.fit.full.sim.simple$Posterior1[,"Sigma_X_Mean"],type="l",main="Sigma_X_Mean")
abline(h=sigma.x.mean)
plot(adapt.fit.full.sim.simple$Posterior1[,"Sigma_X_Std"],type="l",main="Sigma_X_Std")



```